Move install dependancies so failure happens earlier

diff --git a/.github/workflows/merge.yml b/.github/workflows/merge.yml
--- a/.github/workflows/merge.yml
+++ b/.github/workflows/merge.yml
@@ -34,9 +34,6 @@ jobs:
         with:
           node-version: '18'
 
-      - name: Install dependencies
-        run: npm install
-
       - name: Setup version env vars
         run: |
           version=${{ github.event.inputs.version }}
@@ -45,32 +42,34 @@ jobs:
           echo TAG_VERSION="v$version" >> "$GITHUB_ENV"
           echo RELEASE_NOTES_FILE="./release-docs/CFF-${version}.md" >> "$GITHUB_ENV"
 
-      - name: Check PR's approved
-        run: |
-            function prCheck () {
-              REPO=$1
-              BASE=$2
-              gh pr list --repo $REPO --json title,mergeStateStatus,state,reviews --state OPEN --base $BASE --head $RELEASE_BRANCH --jq '.[] | [ select(.mergeStateStatus == "CLEAN" and .reviews[].state == "APPROVED") ]'
-              COUNT=$(gh pr list --repo $REPO --json title,mergeStateStatus,state,reviews --state OPEN --base $BASE --head $RELEASE_BRANCH --jq '.[] | [ select(.mergeStateStatus == "CLEAN" and .reviews[].state == "APPROVED") ] | length ')
-              if [ "$COUNT" -ne 1 ]; then
-                echo "Error: PR for merging $REPO $RELEASE_BRANCH into $BASE needs to be ready to merge and approved." >&2
-                exit 1
-              fi
-            }
-            prCheck $GITHUB_REPOSITORY_OWNER/flood-app master
-            prCheck $GITHUB_REPOSITORY_OWNER/flood-app development
-            prCheck $GITHUB_REPOSITORY_OWNER/flood-service master
-            prCheck $GITHUB_REPOSITORY_OWNER/flood-service development
-        env:
-          # create classic PAT and then run `gh secret set GH_WORKFLOW`
-          GH_TOKEN: ${{ secrets.GH_WORKFLOW }}
-
       - name: Check branch exists
         run: |
           if ! git ls-remote --exit-code origin "refs/heads/${RELEASE_BRANCH}"; then
             echo "Error: Branch ${RELEASE_BRANCH} does not exist." >&2
             exit 1
           fi
+
+      - name: Check PR's approved
+        run: |
+            function prCheck () {
+              REPO=$1
+              BASE=$2
+              STATE=$(gh pr list --repo $GITHUB_REPOSITORY_OWNER/$REPO --json title,mergeStateStatus,state,reviews --state OPEN --base $BASE --head $RELEASE_BRANCH --jq '.[] | select(.mergeStateStatus == "CLEAN" and .reviews[].state == "APPROVED") | .reviews[].state ')
+              if [ "$STATE" != "APPROVED" ]; then
+                echo "Error: PR for merging $GITHUB_REPOSITORY_OWNER/$REPO $RELEASE_BRANCH into $BASE needs to be ready to merge and approved. (STATE=$STATE)" >&2
+                exit 1
+              fi
+            }
+            prCheck flood-app master
+            prCheck flood-app development
+            prCheck flood-service master
+            prCheck flood-service development
+        env:
+          # create classic PAT and then run `gh secret set GH_WORKFLOW`
+          GH_TOKEN: ${{ secrets.GH_WORKFLOW }}
+
+      - name: Install dependencies
+        run: npm install
 
       - name: Merge release branch into master
         run: |
